spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testjpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      매번 테이블 생성
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
#        옵션은 System.out 에 하이버네이트 실행 SQL을 남긴다. sout으로 남긴다.
      # show_sql: true
        format_sql: true

logging.level:
#  옵션은 logger를 통해 하이버네이트 실행 SQL을 남긴다.
  org.hibernate.SQL: debug
  # org.hibernate.type: trace