drop table if exists item CASCADE;
create table item
(
    id bigint generated by default as identity,
    item_name varchar(10),
    price integer,
    quantity integer,
    primary key (id)
);

drop table member if exists cascade;
create table member (
                        member_id varchar(10),
                        login_id varchar(10),
                        name varchar(10),
                        password varchar(10),
                        money integer not null default 0,
                        primary key (member_id)
);